#!/usr/bin/env python3

import os

from pandocfilters import toJSONFilter, Emph, Para, CodeBlock

def file_contents( filename ):
    with open( filename, "r" ) as f:
        return f.read().split("\n")

def dedent( contents, d=0 ):
    return [ i[d:] for i in contents ]

def get_path( meta ):
    try:
       path = meta["pandoc-include-code"]["c"]["path"]["c"][0]["c"]
    except:
       path = ""

    return path

def process(key, value, format, meta):
    if key == "CodeBlock":# and value[0] >= 2:
        [[ident, classes, keyvals], code] = value

        contents = None
        for i in keyvals:
            if i[0] != "include": continue

            filename = os.path.join( get_path( meta ), i[-1] )
            contents = file_contents( filename )

        if contents is None:
            return

        try:
            mn = min( ( int(i[-1]) for i in keyvals if i[0] == "startLine" ) ) -1
        except ValueError: 
            mn = 0

        try:
            mx = min( ( int(i[-1]) for i in keyvals if i[0] == "endLine" ) )
        except ValueError:
            mx = len( contents )

        try:
            d = min( ( int(i[-1]) for i in keyvals if i[0] == "dedent" ) )
        except ValueError: 
            d = 0

        contents = dedent( contents, d )

        return CodeBlock( [ident, classes, keyvals], "\n".join(contents[mn:mx]) )

if __name__ == "__main__":
  toJSONFilter(process)
